# Type dvc-help in this file and hit enter to get more information on how the extension can help to setup pipelines
stages:
  prepare:
    cmd: python src/prepare.py
    deps:
    - src/prepare.py
    params:
    - prepare.data_file
    - prepare.dev_ids
    - prepare.test_ids
    - prepare.icc_results
    - prepare.resampling
    - prepare.binwidth
    - prepare.icc_cut_off
    - prepare.feature_set
    - prepare.variance_threshold
    - prepare.correlation_threshold
    outs:
    - data/dev_set_prepared.pkl
    - data/test_set_prepared.pkl
  train:
    cmd: python src/train.py
    deps:
    - data/dev_set_prepared.pkl
    - data/test_set_prepared.pkl
    - src/train.py
    params:
    - train.model
    - train.n_components
    - train.cost
    - train.svm_gamma
  test:
    cmd: python src/test.py
    deps:
    - data/dev_set_prepared.pkl
    - data/test_set_prepared.pkl
    - src/test.py
    params:
    - test.test
    - test.save_artifacts
    - test.test_results_directory
plots:
- dvclive/plots/metrics:
    x: step
metrics:
- dvclive/metrics.json
