stages:
  data:
    cmd: python src/prepare.py
    deps:
    - src/prepare.py
    params:
    - data.split
    - data.data_file
    - data.dev_ids
    - data.test_ids
    - data.icc_results
    - data.resampling
    - data.binwidth
    - data.icc_cut_off
    - data.feature_set
    - data.variance_threshold
    - data.correlation_threshold
    - data.save_test_artifacts
    outs:
    - data/dev_set_prepared.pkl
    - data/test_set_prepared.pkl
  train:
    cmd: python src/train.py
    deps:
    - data/dev_set_prepared.pkl
    - data/test_set_prepared.pkl
    - src/train.py
    params:
    - train.model
    - train.n_components
    - train.cost
    - train.svm_gamma
    - train.test
  test:
    cmd: python src/test.py
    deps:
    - data/dev_set_prepared.pkl
    - data/test_set_prepared.pkl
    - src/test.py
plots:
- dvclive/plots/images
